### ISSUE TITLE
Template overrides

### ISSUE THREAD

**Issue by robbrandt** [Portugao/MUVideo#13]
I am taking another look at this module.  I see that in docs you have a large number of items in the template overrides files, but I see none of the actual customizations/overrides.  The interface appears to be standard MOST generated.  Am I correct in understanding that you do not supply the customized templates as open source?

**Comment by Portugao** [comment]
Sorry. I don't understand you point.

**Comment by robbrandt** [comment]
Do these custom templates exist?

https://github.com/Portugao/MUVideo/blob/master/docs/overridesTemplate_theme.yml

**Comment by Portugao** [comment]
No!
Please ask @guite about this!

**Comment by Guite** [comment]
See https://github.com/Guite/MostGenerator/issues/460

**Comment by robbrandt** [comment]
Ah, thanks.  A 0.7 feature does this.  Nice, thanks Axel.

So, @Portugao, would a custom set of templates for a nice user interface be a welcome pull request to this project?

**Comment by Portugao** [comment]
@robbrandt 
I think so.
