### ISSUE TITLE
Permissions for all movies in a collection

### ISSUE THREAD

**Issue by robbrandt** [Portugao/MUVideo#20]
I need to restrict access to all movies in a particular collection.  Can't get the settings worked out to make this work.  Suggestions?

**Comment by Portugao** [comment]
You should see the options in the permission module.

**Comment by robbrandt** [comment]
Yes, I know. I've already tried the obvious ones. If you've been successful doing something like thus, can you tell me which option worked?  If not, maybe its a question for Axel...

**Comment by Portugao** [comment]
Which version do you use?

**Comment by Portugao** [comment]
So if you checked this:
```
Gruppe | MUVideo:Collection: | Collection ID:: | kein Zugriff
```
I think it's not impelmented.

**Comment by robbrandt** [comment]
Yes, that was the first one I tried. Axel, what needs to be done for this to work?

**Comment by Portugao** [comment]
This is not within the MOST code. I think I had to do this, if I'm right.

**Comment by Guite** [comment]
Permission checking for related items is done by MOST like this:

In the templates `includeDisplayItemListOne.tpl` and `includeDisplayItemListMany.tpl` are permission checks included. But these use no special permission component, but the normal ones. So if a *person* includes many *addresses*, it checks for `FooModule:Address:` by default.

**Comment by Portugao** [comment]
And the permission scheme above is not implemented, right?

**Comment by robbrandt** [comment]
So to apply my problem to Axel's example, I want to deny a group access to a _person_, and make sure they cannot see any of that person's _addresses_ if addresses are browsed/searched directly.  I would think doing something like 
Group | Modname:Person: | Person ID:: | no access
would do the job.  The relationship between collections and movies in MUVideo mirror this exactly.

Here's the latest template from MUVideo in master:
https://github.com/Portugao/MUVideo/blob/master/templates/movie/includeDisplayItemListMany.tpl
Which doesn't seem to be collection aware.

I am a bit surprised that this in in the template and not in the selection code.  I would think that pagination and other item count functions would show incorrect results if they were included in the data results but excluded at display time.

**Comment by Guite** [comment]
Related items are not count or paginated. They are just shown in a list on the display page of the main item. But of course, you are right. But to solve this very properly we would need some kind of permission filter functionality on Doctrine level. So this affects a more general problem at this point.

**Comment by Portugao** [comment]
So, what is this issue for?

**Comment by Portugao** [comment]
Do you need a way to block this one collection or a way for block several videos for different people or...
If you could specify your needs exactly I could do that.

But see:
In the moment the development depends on a ticket in MOST, because I wish to make the module multilingual.
